# Generated by Django 3.0 on 2021-01-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210123_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
